server:
  port: 8089

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/notice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  #  typeAliasesPackage: com.neuedu.entity
  mapper-locations: classpath*:mapper/*.xml

